### ISSUE TITLE
Fn/for: Send @index on each callback

### ISSUE THREAD

**Issue by urecio** [pixelass/more-or-less#5]
Hi, it could be a great feature to send also the index on the each call back. 

I've done a workaround here: https://github.com/urecio/more-or-less/blob/develop-ur/less/fn/for/_export.less#L8

I'm not a less expert, so probably you will come up with a better solution

**Comment by pixelass** [comment]
Hi thx.. that absolutely makes sense... Though I am currently moving the functions to a different library:  
https://github.com/pixelass/homeless  

The functions from more-or-less will probably be removed in future versions. (or just kept under the hood since they are needed for the prefix mixin)  
Let me think about it a little.

Feel free to add it to this file though: https://github.com/pixelass/homeless/blob/master/src/each/each.less     
Also make sure to write a test for it: https://github.com/pixelass/homeless/blob/master/src/each/each.test.less

I just wrote "homeless" a few days ago so this is the library you should be looking at for functions  ;)

**Comment by pixelass** [comment]
@urecio
I just added it to https://github.com/pixelass/homeless/blob/master/src/each/each.less  
Commit: pixelass/homeless@2ce573c6adb1084141848cdc6a002af83eb03c04

Keeping this issue open.

**Comment by pixelass** [comment]
Closing since repo is deprecated (see readme)
